"""empty message

Revision ID: ed9b4e4430b5
Revises: ac9f5b8b2bd4
Create Date: 2022-04-29 13:56:33.460579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9b4e4430b5'
down_revision = 'ac9f5b8b2bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'peso')
    op.drop_column('users', 'objetivo')
    op.drop_column('users', 'problemasOsseos')
    op.drop_column('users', 'ativo')
    op.drop_column('users', 'altura')
    op.drop_column('users', 'problemasCardiacos')
    op.drop_column('users', 'detalhesProblemas')
    op.drop_column('users', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tipo', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('detalhesProblemas', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('problemasCardiacos', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('altura', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ativo', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('problemasOsseos', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('objetivo', sa.SMALLINT(), nullable=True))
    op.add_column('users', sa.Column('peso', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
